version: '3'
services:
  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile.dev
    image: pa-server
    ports:
      - '80:80'
    networks:
      - pa
  app:
    build:
      context: ../app
      dockerfile: Dockerfile.dev
    image: pa-app
    volumes:
      - ./../app/src:/usr/src/app/src
      - ./../app/dist:/usr/src/app/dist
      - ./../app/build:/usr/src/app/build
      - ./../app/assets:/usr/src/app/assets
    ports:
      - '3000:3000'
    networks:
      - pa
networks:
  pa:
    driver: "bridge"