FROM node:8.1.0-alpine

COPY ./package.json usr/src/app/
COPY ./index.html usr/src/app/
COPY ./.eslintrc.js usr/src/app/

WORKDIR /usr/src/app

RUN yarn install

EXPOSE 3000

CMD ["yarn", "run", "start"]